/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 flower-transformed.glb --types 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    petals: THREE.Mesh
    Sphere: THREE.Mesh
    Sphere001: THREE.Mesh
  }
  materials: {}
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/flower-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.petals.geometry} material={nodes.petals.material} />
      <mesh geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} />
      <mesh geometry={nodes.Sphere001.geometry} material={nodes.Sphere001.material} />
    </group>
  )
}

useGLTF.preload('/flower-transformed.glb')
